name: sample
on:
  push:
    branches:
      - master
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.11
        ports:
          - 3306:3306
        env:
          TZ: UTC
          MYSQL_DATABASE: sample
          MYSQL_USER: sample_user
          MYSQL_PASSWORD: PASSWORD
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
      - name: exec sql
        run: |
          mysql -h 127.0.0.1 -uuser -pPASSWORD -e "SELECT 1"