name: sample
on:
  push:
    branches:
      - master
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          TZ: UTC
          MYSQL_DATABASE: sample
          MYSQL_USER: sample_user
          MYSQL_PASSWORD: PASSWORD
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping -uroot -ppassword" --health-interval 20s --health-timeout 10s --health-retries 10
      redis:
        image: redis:4.0-alpine
        ports:
          - 6379:6379
        env:
          TZ: UTC
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 10
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: foo
          MINIO_SECRET_KEY: bar
          MINIO_REGION: us-east-1
        options: --entrypoint "server /data"
    steps:
      - uses: actions/checkout@v2
      - name: setup database
        run: |
          mysql -h 127.0.0.1 -uroot -ppassword < .github/workflows/scripts/sql/setup.sql
      - name: setup database2
        run: |
          mysql -h 127.0.0.1 -uroot -ppassword < .github/workflows/scripts/sql/setup2.sql
      - name: select dummy data
        run: |
          mysql -h 127.0.0.1 -uroot -ppassword -e "use sample; select * from dummy_table"
      - name: select sample data
        run: |
          mysql -h 127.0.0.1 -uroot -ppassword -e "use sample2; select * from sample_table"
      - name: debug
        run: docker container ls
      - name: restart mysql
        run: docker restart $(docker container ls | grep mysql | awk '{print $1}')