name: sample
on:
  push:
    branches:
      - master
jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        volumes:
          - database:/var/lib/mysql
        env:
          TZ: UTC
          MYSQL_DATABASE: sample
          MYSQL_USER: sample_user
          MYSQL_PASSWORD: PASSWORD
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping -uroot -ppassword" --health-interval 20s --health-timeout 10s --health-retries 10
    steps:
      - name: create table
        run: |
          mysql -h 127.0.0.1 -usample_user -pPASSWORD -e "use sample; create table dummy_table (id int(11) not null auto_increment, title varchar(255) not null, primary key (id))"
      - name: insert dummy data
        run: |
          mysql -h 127.0.0.1 -usample_user -pPASSWORD -e "use sample; insert into dummy_table (title) values ('foo'), ('bar'), ('baz')"